### ISSUE TITLE
Connect string incorrect for Python tutorial on *nix platforms  

### ISSUE THREAD

**Issue by MightyGorilla** [Microsoft/sqldev#34]
Kudos for the great tutorial pages! I just wanted to identify that the connect string shown:

`cnxn = pyodbc.connect('DRIVER={ODBC Driver 13 for SQL Server};SERVER='+server+';PORT=1433;DATABASE='+database+';UID='+username+';PWD='+ password)`

seems to be incorrect. The "PORT=" entry is useless and does nothing. You can set it to any number you like and it still just defaults to 1433. The "SERVER=" entry is where the port must be set. It should look like this: "SERVER=192.168.1.100,15002"

**Comment by ajlam** [comment]
@MightyGorilla, thanks for filling an issue. 

@LuisBosquez or @meet-bhagdev, can you guys take a look?

**Comment by David-Engel** [comment]
Fixed.
