### ISSUE TITLE
Unable to complete configuration of new installation on Linux

### ISSUE THREAD

**Issue by sbushmanov** [Microsoft/sqldev#48]
I'm unsuccessfully trying to complete configuration of newly installed MS-SERVER on Ubuntu 18.04 machine.

My problem basically is follows:
```

[sergey@sergey-Bionic:~$ sudo /opt/mssql/bin/mssql-conf setup’
Traceback (most recent call last):
  File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 15, in <module>
    import mssqlconfhelper
  File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 220
    print _("Setting language using LCID from environment variable %s") % mssqlLcidEnvVariable
          ^
SyntaxError: invalid syntax
sergey@sergey-Bionic:~$ ](url)


```

I attribute inability of the code to complete to those "_" underscores after print statements. Any Ideas where I should move from here?

Any help is really appreciated!

**Comment by David-Engel** [comment]
This GitHub repository isn't meant for providing help with SQL Server issues. There are lots of better options listed in SQL Server docs that will get you in contact with the appropriate experts:
https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017#i-want-to-ask-the-community-for-help
Specifically, this one looks relevant to Setup and upgrade help:
https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlsetupandupgrade&filter=alltypes&sort=lastpostdesc

Regards,
David
