### ISSUE TITLE
contributor-guide folder is missing

### ISSUE THREAD

**Issue by badersur** [Microsoft/sqldev#7]
The following 2 links in the README can't be found:

https://github.com/Microsoft/sqldev/blob/master/contributor-guide/media/documents/markdown-cheatsheet.pdf?raw=true

https://github.com/Microsoft/sqldev/blob/master/contributor-guide/article-metadata.md

**Comment by ajlam** [comment]
@badersur - I've created #10 to fix this. Can you please take a look?

**Comment by badersur** [comment]
Sorry for late reply. These links are fine now but I've found other links to be broken:

https://github.com/Microsoft/sqldev/blob/master/contributor-guide/tools-and-setup.md

https://github.com/Microsoft/sqldev/blob/master/contributor-guide/git-commands-for-master.md

**Comment by ajlam** [comment]
@badersur, can you please check out PR #12? This should address the 2 other broken links you found.

**Comment by badersur** [comment]
@ajlam It looks great :+1:

**Comment by ajlam** [comment]
Awesome. Merging PR #12 now :)

**Comment by ajlam** [comment]
Is it alright to close this issue as well?

**Comment by badersur** [comment]
yep :+1: thanks for asking & fixing it quickly :)

**Comment by ajlam** [comment]
Appreciate you helping to improve these tutorials as well 😄
