### ISSUE TITLE
Are Homebrew & OpenSSL required when Installing .NET Core on Ubuntu?

### ISSUE THREAD

**Issue by badersur** [Microsoft/sqldev#8]
In https://github.com/Microsoft/sqldev/blob/master/pages/csharp/ubuntu/csharp-ubuntu-1.md, there's this:

> If you already have .NET Core installed on your machine, skip this step. Install **Homebrew, OpenSSL**, and .NET Core using the following commands. 

But the command is `sudo apt-get install dotnet-dev-1.0.1` which seems to be for installing .NET Core only.

I'm thinking about sending a PR with:

> If you already have .NET Core installed on your machine, skip this step. Otherwise, install it using the following commands.

but i'm not sure so I'm filling this issue!

BTW, Thanks for publishing the source code for these tutorials. I was looking for it few months ago but couldn't find it. Also, I think it will be easier to contribute if the tutorials link directly to source files.

**Comment by ajlam** [comment]
Hi @badersur, thanks for catching this typo. I've updated the typo with the following commit: https://github.com/Microsoft/sqldev/commit/f5f772d0f4c7916f913c584586e174123de4a9b3

Please feel free to create your own PRs in the future as well. 

We should consider linking the source files from the tutorials. Any recommendations on where in the tutorial we should do that from?

**Comment by badersur** [comment]
Hi @ajlam, You're welcome :)

Thanks for encouraging me to send PRs. I do PRs when I'm 90% sure about it otherwise I file issues.

Regarding the recommendations, I'm not sure but I think it would be nice to have an edit button above the "open chat" button.

**Comment by ajlam** [comment]
Hi @badersur, is it alright with you if we close this issue and create another one to track linking to source files?

**Comment by badersur** [comment]
Hi @ajlam It's totally alright to close it and create another one :)

I'm used to file issues and leave closing them to maintainers. Thanks for being too kind to ask me :blush:
